USE CSD220_TENNIS_CLUB;

CREATE TABLE `MEMBER` AS SELECT * FROM RECREATIONAL_MEMBER;

INSERT INTO MEMBER SELECT `PLAYER_NUMBER`,`FIRST_NAME`,`LAST_NAME`,`SEX`,`YEAR_JOINED`,`PHONE`,`EMAIL` FROM COMPETITIVE_MEMBER;

ALTER TABLE `COMPETITIVE_MEMBER`
	DROP COLUMN FIRST_NAME,
	DROP COLUMN LAST_NAME,
	DROP COLUMN SEX,
	DROP COLUMN PHONE,
	DROP COLUMN EMAIL
	DROP COLUMN YEAR_JOINED;

ALTER TABLE MEMBER ADD PRIMARY KEY (PLAYER_NUMBER);

ALTER TABLE COMPETITIVE_MEMBER ADD FOREIGN KEY (PLAYER_NUMBER) REFERENCES `MEMBER`(PLAYER_NUMBER);

ALTER TABLE `MEMBER` ADD COLUMN `ACTIVE` BOOLEAN NOT NULL;

UPDATE MEMBER SET ACTIVE = TRUE WHERE YEAR_JOINED > NOW() - INTERVAL 5 YEAR;

UPDATE MEMBER SET ACTIVE = FALSE WHERE YEAR_JOINED < NOW() - INTERVAL 5 YEAR;

DROP TABLE RECREATIONAL_MEMBER;

